//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1_Client.ServiceReferenceArticle {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/Zadatak_1_WCF")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceArticle.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewArticles", ReplyAction="http://tempuri.org/IService1/ViewArticlesResponse")]
        Zadatak_1_Client.ServiceReferenceArticle.Article[] ViewArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewArticles", ReplyAction="http://tempuri.org/IService1/ViewArticlesResponse")]
        System.Threading.Tasks.Task<Zadatak_1_Client.ServiceReferenceArticle.Article[]> ViewArticlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArticle", ReplyAction="http://tempuri.org/IService1/AddArticleResponse")]
        bool AddArticle(Zadatak_1_Client.ServiceReferenceArticle.Article article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddArticle", ReplyAction="http://tempuri.org/IService1/AddArticleResponse")]
        System.Threading.Tasks.Task<bool> AddArticleAsync(Zadatak_1_Client.ServiceReferenceArticle.Article article);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Zadatak_1_Client.ServiceReferenceArticle.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Zadatak_1_Client.ServiceReferenceArticle.IService1>, Zadatak_1_Client.ServiceReferenceArticle.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zadatak_1_Client.ServiceReferenceArticle.Article[] ViewArticles() {
            return base.Channel.ViewArticles();
        }
        
        public System.Threading.Tasks.Task<Zadatak_1_Client.ServiceReferenceArticle.Article[]> ViewArticlesAsync() {
            return base.Channel.ViewArticlesAsync();
        }
        
        public bool AddArticle(Zadatak_1_Client.ServiceReferenceArticle.Article article) {
            return base.Channel.AddArticle(article);
        }
        
        public System.Threading.Tasks.Task<bool> AddArticleAsync(Zadatak_1_Client.ServiceReferenceArticle.Article article) {
            return base.Channel.AddArticleAsync(article);
        }
    }
}
